 const SERVERIMAGE = 'https://localhost:44368/'
 const urlApi = 'https://localhost:44368/'

// const SERVERIMAGE = 'https://server.lscloud.vn/'
// const urlApi = 'https://server.lscloud.vn/'

//const SERVERIMAGE = 'https://svtour.lscloud.vn/'
//const urlApi = 'https://svtour.lscloud.vn/'


const URL_AUTHENTICATION_CHECKLOGIN = urlApi + '/api/userinfo/checklogin'
const URL_AUTHENTICATION_LOGIN = urlApi + '/api/userinfo/login'
const URL_AUTHENTICATION_CHANGEPASS = urlApi + '/api/userinfo/changepass'

const URL_COMBOBOX_GETCAUHINHCHUNG = urlApi + '/api/cauhinh/get'
const URL_COMBOBOX_GETQUYEN = urlApi + '/api/userinfo/getquyenbyurl'
const URL_COMBOBOX_GETALLNHANVIEN = urlApi + '/api/baocao/getallnhanvien'
const URL_COMBOBOX_GETLISTNHANVIENBYMULTIIDNHOM = urlApi + '/api/nhanvienapp/getallbynhom'
const URL_COMBOBOX_GETLISTNHANVIENDANGNHAPPHANMEM = urlApi + '/api/nhanvienapp/getnhanviendangnhapphanmem'
const URL_COMBOBOX_GETNHANVIENBYIDNHOM = urlApi + '/api/phienlamviec/getlistnhanvien'
const URL_COMBOBOX_GETALLKHACHHANG = urlApi + '/api/baocao/getallkhachhang'
const URL_COMBOBOX_GETALLKHACHHANG_SERVERPAGING = urlApi + '/api/baocao/getallkhachhang_serverpaging'
const URL_COMBOBOX_GETKHACHHANGBYIDNHANVIEN = urlApi + '/api/kehoachnhanvien/getkhachhangbynhanvien'
const URL_COMBOBOX_GETALLNHOMNHANVIEN = urlApi + '/api/nhomnhanvien/getall'
const URL_COMBOBOX_GETTREENHOMNHANVIEN = urlApi + '/api/nhomnhanvien/treenhom'
const URL_COMBOBOX_GETALLKHUVUC = urlApi + '/api/khuvuc/getall'
const URL_COMBOBOX_GETALLTINHTHANH = urlApi + '/api/tinh/getall'
const URL_COMBOBOX_GETQUANHUYENBYIDTINH = urlApi + '/api/quanhuyen/getbyidtinh'
const URL_COMBOBOX_GETXAPHUONGBYIDQUAN = urlApi + '/api/xaphuong/getbyidquan'
const URL_COMBOBOX_GETALLTUYENKHACHHANG = urlApi + '/api/tuyenkhachhang/getallcombotuyen'
const URL_COMBOBOX_GETALLLOAIKHACHHANG = urlApi + '/api/loaikhachhang/getall'
const URL_COMBOBOX_GETALLKENHBANHANG = urlApi + '/api/kenhbanhang/getall'
const URL_COMBOBOX_GETKENHBANHANGCAPTREN = urlApi + '/api/kenhbanhang/getkenhcaptren'
const URL_COMBOBOX_GETALLMATHANG = urlApi + '/api/mathang/getallcombo'
const URL_COMBOBOX_GETALLMATHANGBYIDNHOM = urlApi + '/api/mathang/getallmathangNew'
const URL_COMBOBOX_GETALLNHOMMATHANG = urlApi + '/api/mathang/getdsnhommathang'
const URL_COMBOBOX_GETTREENHOMMATHANG = urlApi + '/api/mathang/getnhommathang'
const URL_COMBOBOX_GETALLKHOHANG = urlApi + '/api/khohang/getlist'
const URL_COMBOBOX_GETALLKHOHANGBYIDMATHANG = urlApi + 'api/khohang/getbyidhang'
const URL_COMBOBOX_GETALLDONVITINH = urlApi + '/api/mathang/getdsdonvi'
const URL_COMBOBOX_GETALLNHANHIEU = urlApi + '/api/mathang/getdsnhanhieu'
const URL_COMBOBOX_GETALLNHACUNGCAP = urlApi + '/api/mathang/getdsnhacungcap'
const URL_COMBOBOX_GETALLTRANGTHAIDONHANG = urlApi + '/api/donhang/danhSachTrangThaiDonHang'
const URL_COMBOBOX_GETALLTRANGTHAIXEMDONHANG = urlApi + '/api/donhang/getallttx'
const URL_COMBOBOX_GETALLTRANGTHAIGIAOHANGDONHANG = urlApi + '/api/donhang/getallttgh'
const URL_COMBOBOX_GETALLTRANGTHAITHANHTOANDONHANG = urlApi + '/api/donhang/getalltttt'
const URL_COMBOBOX_GETALLTRANGTHAIHOANTATDONHANG = urlApi + '/api/donhang/getallttht'
const URL_COMBOBOX_GETLISTKHUYENMAI = urlApi + '/api/baocao/listkhuyenmai'

const URL_CONGNO_GETLISTKHACHHANG = urlApi + '/api/hanmuc/getdatakhachhang'
const URL_CONGNO_SETNGUONGCONGNOKHACHHANG = urlApi + '/api/hanmuc/setnguongkhachhang'
const URL_CONGNO_GETLISTNHANVIENBYIDNHOM = urlApi + '/api/hanmuc/getdatanhanvien'
const URL_CONGNO_SETNGUONGCONGNONHANVIEN = urlApi + '/api/hanmuc/setnguongnhanvien'
const URL_CONGNO_GETLISTLOAIKHACHHANG = urlApi + '/api/hanmuc/getdataloaikhachhang'
const URL_CONGNO_SETNGUONGCONGNOLOAIKHACHHANG = urlApi + '/api/hanmuc/setnguongloaikhachhang'
const URL_CONGNO_GETLISTNHOMNHANVIEN = urlApi + '/api/hanmuc/getdatanhomnhanvien'
const URL_CONGNO_SETNGUONGCONGNONHOMNHANVIEN = urlApi + '/api/hanmuc/setnguongnhomnhanvien'